//! Integration tests for the agent loop and event processing pipeline.
//!
//! These tests use a deterministic mock LLM provider to verify the full
//! Event → LLM → Sandbox → SkillExecutor → Response chain without real API calls.

use std::sync::Arc;
use tokio::sync::Mutex;

use async_trait::async_trait;
use kittypaw_core::config::Config;
use kittypaw_core::error::Result;
use kittypaw_core::types::{Event, EventType, LlmMessage};
use kittypaw_llm::provider::{LlmProvider, LlmResponse};
use kittypaw_sandbox::Sandbox;
use kittypaw_store::Store;

// ── Mock LLM Provider ──────────────────────────────────────────────────

/// A mock provider that returns pre-determined JS code as if generated by an LLM.
struct MockJsProvider {
    js_code: String,
}

impl MockJsProvider {
    fn new(js: &str) -> Self {
        Self {
            js_code: js.to_string(),
        }
    }
}

#[async_trait]
impl LlmProvider for MockJsProvider {
    async fn generate(&self, _messages: &[LlmMessage]) -> Result<LlmResponse> {
        Ok(LlmResponse::text_only(self.js_code.clone()))
    }
}

// ── Helpers ─────────────────────────────────────────────────────────────

fn test_config() -> Config {
    let mut config = Config::default();
    config.freeform_fallback = true; // allow natural language → agent_loop
    config
}

fn telegram_event(text: &str, chat_id: &str) -> Event {
    Event {
        event_type: EventType::Telegram,
        payload: serde_json::json!({
            "text": text,
            "chat_id": chat_id,
            "from_name": "test_user",
        }),
    }
}

fn desktop_event(text: &str) -> Event {
    Event {
        event_type: EventType::Desktop,
        payload: serde_json::json!({
            "text": text,
            "workspace_id": "test",
        }),
    }
}

// ── Tests ───────────────────────────────────────────────────────────────

/// Agent loop processes a simple return statement and produces output.
#[tokio::test]
async fn test_agent_loop_simple_return() {
    let provider = MockJsProvider::new(r#"return "hello from agent";"#);
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store: store.clone(),
        config: &config,
        on_token: None,
        on_permission_request: None,
    };

    let event = desktop_event("say hello");
    let result = session.run(event).await;
    assert!(result.is_ok(), "agent_loop should succeed: {:?}", result);
    assert_eq!(result.unwrap(), "hello from agent");
}

/// Agent loop handles Storage.get/set skill calls within sandbox execution.
#[tokio::test]
async fn test_agent_loop_storage_round_trip() {
    let provider = MockJsProvider::new(
        r#"
        await Storage.set("greeting", "world");
        const val = await Storage.get("greeting");
        return "stored: " + val;
        "#,
    );
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store: store.clone(),
        config: &config,
        on_token: None,
        on_permission_request: None,
    };

    let result = session.run(desktop_event("store something")).await;
    assert!(result.is_ok(), "storage round-trip: {:?}", result);
    let text = result.unwrap();
    // Storage.get returns JSON {"value":"world"}, so the concatenation includes it
    assert!(
        text.contains("world"),
        "expected stored value containing 'world', got: {text}"
    );
}

/// Agent loop creates a session/agent state that persists across calls.
#[tokio::test]
async fn test_agent_session_state_persists() {
    let provider = MockJsProvider::new(r#"return "ok";"#);
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store: store.clone(),
        config: &config,
        on_token: None,
        on_permission_request: None,
    };

    // First call creates state
    let r1 = session.run(desktop_event("first")).await;
    assert!(r1.is_ok());

    // Second call reuses state — agent should have 2 user turns + 2 assistant turns
    let r2 = session.run(desktop_event("second")).await;
    assert!(r2.is_ok());

    // Verify state was persisted
    let s = store.lock().await;
    let state = s
        .load_state("desktop-test")
        .expect("load_state")
        .expect("state should exist");
    // 2 user turns + 2 assistant turns = 4 total
    assert!(
        state.turns.len() >= 4,
        "expected >= 4 turns, got {}",
        state.turns.len()
    );
}

/// Telegram events use chat_id as agent_id prefix.
#[tokio::test]
async fn test_telegram_event_creates_agent_id() {
    let provider = MockJsProvider::new(r#"return "tg ok";"#);
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store: store.clone(),
        config: &config,
        on_token: None,
        on_permission_request: None,
    };

    let event = telegram_event("hello", "12345");
    let result = session.run(event).await;
    assert!(result.is_ok());

    let s = store.lock().await;
    let state = s.load_state("telegram-12345").expect("load_state");
    assert!(state.is_some(), "telegram agent state should be created");
}

/// Bootstrap parity: Config::default() produces a valid config that
/// AgentSession can use without panicking.
#[tokio::test]
async fn test_bootstrap_parity_default_config() {
    let config = Config::default();

    // Verify essential fields have sane defaults
    assert!(config.sandbox.timeout_secs > 0);
    assert!(config.sandbox.memory_limit_mb > 0);
    assert!(config.sandbox.allowed_paths.is_empty()); // backward compat: no restrictions
    assert!(config.agents.is_empty());
    assert!(config.channels.is_empty());

    // Verify Store can be opened with in-memory path
    let store = Store::open(":memory:");
    assert!(store.is_ok(), "in-memory store should open");

    // Verify Sandbox can be created from config
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    // Simple execution should work without panicking
    let result = sandbox.execute("return 42;", serde_json::json!({})).await;
    assert!(result.is_ok(), "sandbox should execute: {:?}", result);
}

/// When freeform_fallback is false, non-slash messages without a matching
/// skill trigger return a helpful message instead of invoking the LLM.
#[tokio::test]
async fn test_freeform_fallback_disabled() {
    let provider = MockJsProvider::new(r#"return "should not reach";"#);
    let mut config = test_config();
    config.freeform_fallback = false;
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store,
        config: &config,
        on_token: None,
        on_permission_request: None,
    };

    let result = session.run(desktop_event("hello")).await;
    assert!(result.is_ok());
    let text = result.unwrap();
    assert!(
        text.contains("스킬") || text.contains("teach"),
        "should suggest /teach, got: {text}"
    );
}

/// LLM returning invalid JS causes graceful retry/failure, not a panic.
#[tokio::test]
async fn test_agent_loop_handles_invalid_js() {
    let provider = MockJsProvider::new("this is not valid javascript {{{}}}");
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store: store.clone(),
        config: &config,
        on_token: None,
        on_permission_request: None,
    };

    // Should not panic — may return error or empty string after retries
    let result = session.run(desktop_event("do something")).await;
    // The agent loop retries 3 times with the same broken JS, then returns an error
    assert!(
        result.is_err(),
        "invalid JS should eventually error, not panic"
    );
}
