name = "kittypaw-relay"
main = "src/index.ts"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "MESSAGES"
id = "e451443f9a944cf597275cd1deb2bdc4"
preview_id = "e451443f9a944cf597275cd1deb2bdc4"

[vars]
# WEBHOOK_SECRET is set via `wrangler secret put WEBHOOK_SECRET`
